### ISSUE TITLE
Fixing internet explorer

### ISSUE THREAD

**Issue by hubyeti** [matthewmccullough/github-skills-assessment-1#2]
We really need to fix internet explorer!

**Comment by hubchupacabra** [comment]
I think Microsoft needs to fix internet explorer. :smile:
        But I do agree that we should make this look OK in IE9+ as we have a bunch of corporate users.

**Comment by matthewmccullough** [comment]
Hey @1point618, @crichID  (CC @PeterBell).  There's a good chance we can get a chunk of Microsoft employees on this platform as well (fingers crossed).  I think it might resonate better with them if we have something more generic as the concern than "Internet Explorer."  I totally get the sentiment and stopped optimizing for it years ago, but we don't want any Microsof hurt feelings getting in the way of learning.  I leave it in your curriculum-designing hands to see if there's a quick tweak on wording we can get in here.

**Comment by 1point618** [comment]
@matthewmccullough  Makes perfect sense, we will take care of this asap.

**Comment by crichID** [comment]
@1point618 I also dropped an issue in the githubpartners/wheelhouse repo!

**Comment by matthewmccullough** [comment]
@crichID @1point618 Thank you both for being so welcoming of my late posting of this sentiment.
